- name: test module stat et register
  hosts: all
  remote_user: teddy
  become: yes
#  become_user: yes

  tasks: 
  - name: cr√©ation de user-ansible
    user:
      name: user-ansible
      state: present
      uid: 1200
      shell: /bin/bash 
      groups: sudo
      append: yes
      password: "{{ 'Ansibl30' | password_hash('sha512') }}"  

    
   
  
